version: '3.1'
services:
  mongo:
    image: mongo:4.2
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: leanote
      MONGO_INITDB_DATABASE: leanote
    volumes:
      - ./mongodb:/data/db
      - ./leanote_install_data:/leanote_install_data
      - ./dbinit.sh:/docker-entrypoint-initdb.d/dbinit.sh
      - ./leanote.js:/leanote.js

  leanote:
    depends_on:
     - mongo
    links:
     - mongo:mongodb
    image: mw/leanote:2
    restart: always
    container_name: leanote
    volumes:
      - ./datas/files:/leanote/files
      - ./datas/upload:/leanote/public/upload
      - ./app.conf:/leanote/conf/app.conf
    ports:
      - 4809:9000 
