version: '3.1'
services:
  mongo:
    image: mongo:4.2
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: leanote
      MONGO_INITDB_DATABASE: leanote
    volumes:
      - ./mongodb/opt/:/opt/
      - ./mongodb/db/:/data/db/
      - ./mongodb/leanote_install_data/:/leanote_install_data/  
      - ./mongodb/dbinit.sh:/docker-entrypoint-initdb.d/dbinit.sh
      - ./mongodb/leanote.js:/leanote.js

  leanote:
    depends_on:
     - mongo
    links:
     - mongo:mongodb
    image: p.mwpub.site:4041/public/leanote:2.6.1
    restart: always
    container_name: leanote
    volumes:
      - ./leanote_data/files/:/leanote/files/
      - ./leanote_data/upload/:/leanote/public/upload/
      - ./leanote_data/conf/app.conf:/leanote/conf/app.conf
    ports:
      - 4809:9000 
